// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file autokitteh/user_code/v1/user_code.proto (package autokitteh.user_code.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file autokitteh/user_code/v1/user_code.proto.
 */
export const file_autokitteh_user_code_v1_user_code: GenFile = /*@__PURE__*/
  fileDesc("CidhdXRva2l0dGVoL3VzZXJfY29kZS92MS91c2VyX2NvZGUucHJvdG8SF2F1dG9raXR0ZWgudXNlcl9jb2RlLnYxIkUKBUZyYW1lEhAKCGZpbGVuYW1lGAEgASgJEg4KBmxpbmVubxgCIAEoDRIMCgRjb2RlGAMgASgJEgwKBG5hbWUYBCABKAkiFQoFRXZlbnQSDAoEZGF0YRgBIAEoDEL1AQobY29tLmF1dG9raXR0ZWgudXNlcl9jb2RlLnYxQg1Vc2VyQ29kZVByb3RvUAFaTWdvLmF1dG9raXR0ZWguZGV2L2F1dG9raXR0ZWgvcHJvdG8vZ2VuL2dvL2F1dG9raXR0ZWgvdXNlcl9jb2RlL3YxO3VzZXJfY29kZXYxogIDQVVYqgIWQXV0b2tpdHRlaC5Vc2VyQ29kZS5WMcoCFkF1dG9raXR0ZWhcVXNlckNvZGVcVjHiAiJBdXRva2l0dGVoXFVzZXJDb2RlXFYxXEdQQk1ldGFkYXRh6gIYQXV0b2tpdHRlaDo6VXNlckNvZGU6OlYxYgZwcm90bzM");

/**
 * @generated from message autokitteh.user_code.v1.Frame
 */
export type Frame = Message<"autokitteh.user_code.v1.Frame"> & {
  /**
   * @generated from field: string filename = 1;
   */
  filename: string;

  /**
   * @generated from field: uint32 lineno = 2;
   */
  lineno: number;

  /**
   * @generated from field: string code = 3;
   */
  code: string;

  /**
   * @generated from field: string name = 4;
   */
  name: string;
};

/**
 * Describes the message autokitteh.user_code.v1.Frame.
 * Use `create(FrameSchema)` to create a new message.
 */
export const FrameSchema: GenMessage<Frame> = /*@__PURE__*/
  messageDesc(file_autokitteh_user_code_v1_user_code, 0);

/**
 * @generated from message autokitteh.user_code.v1.Event
 */
export type Event = Message<"autokitteh.user_code.v1.Event"> & {
  /**
   * raw event from connection
   *
   * @generated from field: bytes data = 1;
   */
  data: Uint8Array;
};

/**
 * Describes the message autokitteh.user_code.v1.Event.
 * Use `create(EventSchema)` to create a new message.
 */
export const EventSchema: GenMessage<Event> = /*@__PURE__*/
  messageDesc(file_autokitteh_user_code_v1_user_code, 1);

