# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

builds:
  - id: ak
    binary: ak
    main: ./cmd/ak
    ldflags:
      - -X 'go.autokitteh.dev/autokitteh/internal/version.Version={{ .Version }}'
      - -X 'go.autokitteh.dev/autokitteh/internal/version.Date={{ .Date }}'
      - -X 'go.autokitteh.dev/autokitteh/internal/version.Commit={{ .Commit }}'
      - -X 'go.autokitteh.dev/autokitteh/internal/version.User=goreleaser'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

brews:
  - name: autokitteh
    description: "Durable workflow automation made simple"
    homepage: "https://autokitteh.com"
    url_template: "https://github.com/autokitteh/autokitteh/releases/download/{{ .Version }}/{{ .ArtifactName }}"
    license: "Apache-2.0"
    install: |
      bin.install "ak"
    test: |
      system "#{bin}/ak --version"
    repository:
      owner: autokitteh
      name: homebrew-tap
      branch: main

source:
  enabled: false

release:
  prerelease: auto

archives:
  - files:
      - none*
    format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ tolower .ProjectName }}_{{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
