# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

builds:
  - id: ak
    binary: ak
    main: ./cmd/ak
    ldflags:
      - -X 'go.autokitteh.dev/autokitteh/internal/version.Version={{ .Version }}'
      - -X 'go.autokitteh.dev/autokitteh/internal/version.Date={{ .Date }}'
      - -X 'go.autokitteh.dev/autokitteh/internal/version.Commit={{ .Commit }}'
      - -X 'go.autokitteh.dev/autokitteh/internal/version.User=goreleaser'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

source:
  enabled: false

release:
  prerelease: auto

archives:
  - files:
      - none*
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ tolower .ProjectName }}_{{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
