[files]
extend-exclude = [
    "descope-web-component.js",
    "vanilla-jsoneditor.js",
    "internal/backend/dashboardsvc/render_list.go",
    "runtimes/pythonrt/build_test.go",
    "sdk/sdktypes/integration_id_test.go",
    "go.mod",
    "internal/backend/auth/authtokens/authjwttokens/jwt_test.go"
]

[default.extend-identifiers]
typ = "typ"
