[files]
extend-exclude = [
    "descope-web-component.js",
    "vanilla-jsoneditor.js",
    "internal/backend/dashboardsvc/render_list.go",
    "runtimes/pythonrt/build_test.go",
    "sdk/sdktypes/integration_id_test.go"
]
