# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
      target: final
    command: ["up", "--mode=dev"]
    ports:
      - 9980:9980
      - 9982:9982
    # Enable this to provide environment variables overrides
    # environment:
    #   # default is localhost:7233
    #   AK_TEMPORALCLIENT__HOSTPORT: "localhost:7233"
    #   # default value is default
    #   AK_TEMPORALCLIENT__NAMESPACE: "default"
    #   # default value is false, enable if your temporal server requires tls
    #   # if tls is enabled, you must provide either certificate and key inline or as file paths
    #   # if you provide both, the inline certificate takes precedence and the files are ignored
    #   AK_TEMPORALCLIENT__TLS__ENABLED: "true"
    #   # inline certificate
    #   AK_TEMPORALCLIENT__TLS__CERTIFICATE: "<inline certificate>"
    #   # inline key
    #   AK_TEMPORALCLIENT__TLS__KEY: "<inline prinvate key>"
    #   # Certificate as path
    #   AK_TEMPORALCLIENT__TLS__CERTIFICATE_FILE_PATH: "<path>"
    #   # Key as path
    #   AK_TEMPORALCLIENT__TLS__KEY_FILE_PATH: "<path>"
    #   # Can be either postgres or sqlite, default is sqlite
    #   AK_DB__TYPE: "postgres"
    #   # for sqlite, can be sqlite://<path_to_file> in case you want a persistence sqlite, otherwise the default is in memory
    #   # for postgres, provide a valid dsn, not all options required "host= dbname= user= password= sslmode= TimeZone"
    #   AK_DB__DSN: "host=localhost dbname=autokitteh"
