# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.autokitteh.user_code.v1 import runner_svc_pb2 as autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2


class RunnerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Exports = channel.unary_unary(
                '/autokitteh.user_code.v1.RunnerService/Exports',
                request_serializer=autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.ExportsRequest.SerializeToString,
                response_deserializer=autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.ExportsResponse.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/autokitteh.user_code.v1.RunnerService/Start',
                request_serializer=autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.StartRequest.SerializeToString,
                response_deserializer=autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.StartResponse.FromString,
                _registered_method=True)
        self.Execute = channel.unary_unary(
                '/autokitteh.user_code.v1.RunnerService/Execute',
                request_serializer=autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.ActivityReply = channel.unary_unary(
                '/autokitteh.user_code.v1.RunnerService/ActivityReply',
                request_serializer=autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.ActivityReplyRequest.SerializeToString,
                response_deserializer=autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.ActivityReplyResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/autokitteh.user_code.v1.RunnerService/Health',
                request_serializer=autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.RunnerHealthRequest.SerializeToString,
                response_deserializer=autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.RunnerHealthResponse.FromString,
                _registered_method=True)


class RunnerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Exports(self, request, context):
        """Get exports
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Called at start of session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Execute a function in the runtime (skipped if it's a reply)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivityReply(self, request, context):
        """Reply from activity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RunnerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Exports': grpc.unary_unary_rpc_method_handler(
                    servicer.Exports,
                    request_deserializer=autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.ExportsRequest.FromString,
                    response_serializer=autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.ExportsResponse.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.StartRequest.FromString,
                    response_serializer=autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.StartResponse.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.ExecuteRequest.FromString,
                    response_serializer=autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.ExecuteResponse.SerializeToString,
            ),
            'ActivityReply': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivityReply,
                    request_deserializer=autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.ActivityReplyRequest.FromString,
                    response_serializer=autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.ActivityReplyResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.RunnerHealthRequest.FromString,
                    response_serializer=autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.RunnerHealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autokitteh.user_code.v1.RunnerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('autokitteh.user_code.v1.RunnerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RunnerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Exports(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autokitteh.user_code.v1.RunnerService/Exports',
            autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.ExportsRequest.SerializeToString,
            autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.ExportsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autokitteh.user_code.v1.RunnerService/Start',
            autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.StartRequest.SerializeToString,
            autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.StartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autokitteh.user_code.v1.RunnerService/Execute',
            autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.ExecuteRequest.SerializeToString,
            autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActivityReply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autokitteh.user_code.v1.RunnerService/ActivityReply',
            autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.ActivityReplyRequest.SerializeToString,
            autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.ActivityReplyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autokitteh.user_code.v1.RunnerService/Health',
            autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.RunnerHealthRequest.SerializeToString,
            autokitteh_dot_user__code_dot_v1_dot_runner__svc__pb2.RunnerHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
