# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: autokitteh/user_code/v1/user_code.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'autokitteh/user_code/v1/user_code.proto\x12\x17\x61utokitteh.user_code.v1\"c\n\x05\x46rame\x12\x1a\n\x08\x66ilename\x18\x01 \x01(\tR\x08\x66ilename\x12\x16\n\x06lineno\x18\x02 \x01(\rR\x06lineno\x12\x12\n\x04\x63ode\x18\x03 \x01(\tR\x04\x63ode\x12\x12\n\x04name\x18\x04 \x01(\tR\x04name\"\x1b\n\x05\x45vent\x12\x12\n\x04\x64\x61ta\x18\x01 \x01(\x0cR\x04\x64\x61taB\xf5\x01\n\x1b\x63om.autokitteh.user_code.v1B\rUserCodeProtoP\x01ZMgo.autokitteh.dev/autokitteh/proto/gen/go/autokitteh/user_code/v1;user_codev1\xa2\x02\x03\x41UX\xaa\x02\x16\x41utokitteh.UserCode.V1\xca\x02\x16\x41utokitteh\\UserCode\\V1\xe2\x02\"Autokitteh\\UserCode\\V1\\GPBMetadata\xea\x02\x18\x41utokitteh::UserCode::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autokitteh.user_code.v1.user_code_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033com.autokitteh.user_code.v1B\rUserCodeProtoP\001ZMgo.autokitteh.dev/autokitteh/proto/gen/go/autokitteh/user_code/v1;user_codev1\242\002\003AUX\252\002\026Autokitteh.UserCode.V1\312\002\026Autokitteh\\UserCode\\V1\342\002\"Autokitteh\\UserCode\\V1\\GPBMetadata\352\002\030Autokitteh::UserCode::V1'
  _globals['_FRAME']._serialized_start=68
  _globals['_FRAME']._serialized_end=167
  _globals['_EVENT']._serialized_start=169
  _globals['_EVENT']._serialized_end=196
# @@protoc_insertion_point(module_scope)
