"""Filter warning generated by protobuf.

Once they upgrade reflection we can remove this.
"""

from warnings import filterwarnings

filterwarnings(
    action="ignore",
    category=UserWarning,
    message="Protobuf gencode",
)
