#!/bin/bash

set -euo pipefail

root="gen/py/autokitteh_pb"
mv "gen/py/autokitteh" "${root}"

dirs=$(find ${root} -type d | sed -n -E '/\/v1$/p' | sort) # only dirs ending with v1.

autogen_comment="# This file is autogenerated by fixpy.sh\n\n"

names=""
for dir in $dirs; do
    name=$(basename "$(dirname "$dir")")
    names=$(echo -e "${names}\n${name}\n")
    echo -e "${autogen_comment}from . import $name\n" > "${dir}/../../__init__.py"
done

quoted=$(echo -e "$names" | sed -E '/^$/d; s/(.*)/"\1"/g' | tr '\n' ',')

echo -e "\n\n__all__=[$quoted]" >> "${root}/__init__.py"

# This adds imports and __all__ to each relevant __init__.py file.
for dir in $dirs; do
    files=$(find "$dir"/* | sed -E "/__init__.py/d; s/\.py$//g; s/\.pyi$//g" | sort -u)

    initfn="$dir/__init__.py"

    echo -e "${autogen_comment}from . import v1\n\n__all__ = ['v1']" > "$dir/../__init__.py"

    echo -e "${autogen_comment}" > "$initfn"

    all=""

    for file in $files; do
        symbols=$(cat "$file.py"* | sed -n -E 's/^class (.*)\(.*/\1/p')

        all=$(echo -e "${symbols}\n${all}")

        [[ -z $symbols ]] && continue

        commas=$(echo "$symbols" | tr '\n' ',')

        echo "from .$(basename "$file") import ($commas)" >> "$initfn"

        if [[ -r $file.py ]]; then
            sed -E 's/from autokitteh\./from autokitteh_pb./g' < "$file.py" > "$file.py.new"
            mv "$file.py.new" "$file.py"
        fi

        if [[ -r $file.pyi ]]; then
            sed -E 's/from autokitteh\./from autokitteh_pb./g' < "$file.pyi" > "$file.pyi.new"
            mv "$file.pyi.new" "$file.pyi"
        fi
    done

    quoted=$(echo -e "$all" | sed -E '/^$/d; s/(.*)/"\1"/g' | tr '\n' ',')

    echo -e "\n\n__all__ = [$quoted]" >> "$initfn"
done
