// @generated by protoc-gen-connect-es v1.1.4 with parameter "target=ts"
// @generated from file autokitteh/user_code/v1/handler_svc.proto (package autokitteh.user_code.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ActivityRequest, ActivityResponse, DoneRequest, DoneResponse, EncodeJWTRequest, EncodeJWTResponse, HandlerHealthRequest, HandlerHealthResponse, IsActiveRunnerRequest, IsActiveRunnerResponse, LogRequest, LogResponse, NextEventRequest, NextEventResponse, PrintRequest, PrintResponse, RefreshRequest, RefreshResponse, SleepRequest, SleepResponse, StartSessionRequest, StartSessionResponse, SubscribeRequest, SubscribeResponse, UnsubscribeRequest, UnsubscribeResponse } from "./handler_svc_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service autokitteh.user_code.v1.HandlerService
 */
export const HandlerService = {
  typeName: "autokitteh.user_code.v1.HandlerService",
  methods: {
    /**
     * Runner starting activity
     *
     * @generated from rpc autokitteh.user_code.v1.HandlerService.Activity
     */
    activity: {
      name: "Activity",
      I: ActivityRequest,
      O: ActivityResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Runner done with activity
     *
     * @generated from rpc autokitteh.user_code.v1.HandlerService.Done
     */
    done: {
      name: "Done",
      I: DoneRequest,
      O: DoneResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Session logs
     *
     * @generated from rpc autokitteh.user_code.v1.HandlerService.Log
     */
    log: {
      name: "Log",
      I: LogRequest,
      O: LogResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Print to session log
     *
     * @generated from rpc autokitteh.user_code.v1.HandlerService.Print
     */
    print: {
      name: "Print",
      I: PrintRequest,
      O: PrintResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ak functions
     *
     * @generated from rpc autokitteh.user_code.v1.HandlerService.Sleep
     */
    sleep: {
      name: "Sleep",
      I: SleepRequest,
      O: SleepResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc autokitteh.user_code.v1.HandlerService.Subscribe
     */
    subscribe: {
      name: "Subscribe",
      I: SubscribeRequest,
      O: SubscribeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc autokitteh.user_code.v1.HandlerService.NextEvent
     */
    nextEvent: {
      name: "NextEvent",
      I: NextEventRequest,
      O: NextEventResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc autokitteh.user_code.v1.HandlerService.Unsubscribe
     */
    unsubscribe: {
      name: "Unsubscribe",
      I: UnsubscribeRequest,
      O: UnsubscribeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc autokitteh.user_code.v1.HandlerService.StartSession
     */
    startSession: {
      name: "StartSession",
      I: StartSessionRequest,
      O: StartSessionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Utility functions
     *
     * @generated from rpc autokitteh.user_code.v1.HandlerService.EncodeJWT
     */
    encodeJWT: {
      name: "EncodeJWT",
      I: EncodeJWTRequest,
      O: EncodeJWTResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc autokitteh.user_code.v1.HandlerService.RefreshOAuthToken
     */
    refreshOAuthToken: {
      name: "RefreshOAuthToken",
      I: RefreshRequest,
      O: RefreshResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc autokitteh.user_code.v1.HandlerService.Health
     */
    health: {
      name: "Health",
      I: HandlerHealthRequest,
      O: HandlerHealthResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc autokitteh.user_code.v1.HandlerService.IsActiveRunner
     */
    isActiveRunner: {
      name: "IsActiveRunner",
      I: IsActiveRunnerRequest,
      O: IsActiveRunnerResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

