// @generated by protoc-gen-connect-es v1.1.4 with parameter "target=ts"
// @generated from file autokitteh/user_code/v1/runner_svc.proto (package autokitteh.user_code.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ActivityReplyRequest, ActivityReplyResponse, ExecuteRequest, ExecuteResponse, ExportsRequest, ExportsResponse, RunnerHealthRequest, RunnerHealthResponse, StartRequest, StartResponse } from "./runner_svc_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service autokitteh.user_code.v1.RunnerService
 */
export const RunnerService = {
  typeName: "autokitteh.user_code.v1.RunnerService",
  methods: {
    /**
     * Get exports
     *
     * @generated from rpc autokitteh.user_code.v1.RunnerService.Exports
     */
    exports: {
      name: "Exports",
      I: ExportsRequest,
      O: ExportsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Called at start of session
     *
     * @generated from rpc autokitteh.user_code.v1.RunnerService.Start
     */
    start: {
      name: "Start",
      I: StartRequest,
      O: StartResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Execute a function in the runtime (skipped if it's a reply)
     *
     * @generated from rpc autokitteh.user_code.v1.RunnerService.Execute
     */
    execute: {
      name: "Execute",
      I: ExecuteRequest,
      O: ExecuteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Reply from activity
     *
     * @generated from rpc autokitteh.user_code.v1.RunnerService.ActivityReply
     */
    activityReply: {
      name: "ActivityReply",
      I: ActivityReplyRequest,
      O: ActivityReplyResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc autokitteh.user_code.v1.RunnerService.Health
     */
    health: {
      name: "Health",
      I: RunnerHealthRequest,
      O: RunnerHealthResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

