// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file autokitteh/module/v1/module.proto (package autokitteh.module.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file autokitteh/module/v1/module.proto.
 */
export const file_autokitteh_module_v1_module: GenFile = /*@__PURE__*/
  fileDesc("CiFhdXRva2l0dGVoL21vZHVsZS92MS9tb2R1bGUucHJvdG8SFGF1dG9raXR0ZWgubW9kdWxlLnYxItQCCgZNb2R1bGUSUgoJZnVuY3Rpb25zGAEgAygLMisuYXV0b2tpdHRlaC5tb2R1bGUudjEuTW9kdWxlLkZ1bmN0aW9uc0VudHJ5QhL69xgOmgELIgRyAhABKgPIAQESUgoJdmFyaWFibGVzGAIgAygLMisuYXV0b2tpdHRlaC5tb2R1bGUudjEuTW9kdWxlLlZhcmlhYmxlc0VudHJ5QhL69xgOmgELIgRyAhABKgPIAQEaUAoORnVuY3Rpb25zRW50cnkSCwoDa2V5GAEgASgJEi0KBXZhbHVlGAIgASgLMh4uYXV0b2tpdHRlaC5tb2R1bGUudjEuRnVuY3Rpb246AjgBGlAKDlZhcmlhYmxlc0VudHJ5EgsKA2tleRgBIAEoCRItCgV2YWx1ZRgCIAEoCzIeLmF1dG9raXR0ZWgubW9kdWxlLnYxLlZhcmlhYmxlOgI4ASIfCghWYXJpYWJsZRITCgtkZXNjcmlwdGlvbhgBIAEoCSLwAQoIRnVuY3Rpb24SEwoLZGVzY3JpcHRpb24YASABKAkSGQoRZG9jdW1lbnRhdGlvbl91cmwYAiABKAkSMgoFaW5wdXQYAyADKAsyIy5hdXRva2l0dGVoLm1vZHVsZS52MS5GdW5jdGlvbkZpZWxkEjMKBm91dHB1dBgEIAMoCzIjLmF1dG9raXR0ZWgubW9kdWxlLnYxLkZ1bmN0aW9uRmllbGQSLwoIZXhhbXBsZXMYBSADKAsyHS5hdXRva2l0dGVoLm1vZHVsZS52MS5FeGFtcGxlEhoKEmRlcHJlY2F0ZWRfbWVzc2FnZRgGIAEoCSKzAQoNRnVuY3Rpb25GaWVsZBIWCgRuYW1lGAEgASgJQgj69xgEcgIQARITCgtkZXNjcmlwdGlvbhgCIAEoCRIMCgR0eXBlGAMgASgJEhAKCG9wdGlvbmFsGAQgASgIEhUKDWRlZmF1bHRfdmFsdWUYBSABKAkSDQoFa3dhcmcYBiABKAgSLwoIZXhhbXBsZXMYByADKAsyHS5hdXRva2l0dGVoLm1vZHVsZS52MS5FeGFtcGxlIiwKB0V4YW1wbGUSDAoEY29kZRgBIAEoCRITCgtleHBsYW5hdGlvbhgCIAEoCULiAQoYY29tLmF1dG9raXR0ZWgubW9kdWxlLnYxQgtNb2R1bGVQcm90b1ABWkdnby5hdXRva2l0dGVoLmRldi9hdXRva2l0dGVoL3Byb3RvL2dlbi9nby9hdXRva2l0dGVoL21vZHVsZS92MTttb2R1bGV2MaICA0FNWKoCFEF1dG9raXR0ZWguTW9kdWxlLlYxygIUQXV0b2tpdHRlaFxNb2R1bGVcVjHiAiBBdXRva2l0dGVoXE1vZHVsZVxWMVxHUEJNZXRhZGF0YeoCFkF1dG9raXR0ZWg6Ok1vZHVsZTo6VjFiBnByb3RvMw", [file_buf_validate_validate]);

/**
 * @generated from message autokitteh.module.v1.Module
 */
export type Module = Message<"autokitteh.module.v1.Module"> & {
  /**
   * @generated from field: map<string, autokitteh.module.v1.Function> functions = 1;
   */
  functions: { [key: string]: Function };

  /**
   * @generated from field: map<string, autokitteh.module.v1.Variable> variables = 2;
   */
  variables: { [key: string]: Variable };
};

/**
 * Describes the message autokitteh.module.v1.Module.
 * Use `create(ModuleSchema)` to create a new message.
 */
export const ModuleSchema: GenMessage<Module> = /*@__PURE__*/
  messageDesc(file_autokitteh_module_v1_module, 0);

/**
 * @generated from message autokitteh.module.v1.Variable
 */
export type Variable = Message<"autokitteh.module.v1.Variable"> & {
  /**
   * @generated from field: string description = 1;
   */
  description: string;
};

/**
 * Describes the message autokitteh.module.v1.Variable.
 * Use `create(VariableSchema)` to create a new message.
 */
export const VariableSchema: GenMessage<Variable> = /*@__PURE__*/
  messageDesc(file_autokitteh_module_v1_module, 1);

/**
 * @generated from message autokitteh.module.v1.Function
 */
export type Function = Message<"autokitteh.module.v1.Function"> & {
  /**
   * @generated from field: string description = 1;
   */
  description: string;

  /**
   * @generated from field: string documentation_url = 2;
   */
  documentationUrl: string;

  /**
   * @generated from field: repeated autokitteh.module.v1.FunctionField input = 3;
   */
  input: FunctionField[];

  /**
   * @generated from field: repeated autokitteh.module.v1.FunctionField output = 4;
   */
  output: FunctionField[];

  /**
   * @generated from field: repeated autokitteh.module.v1.Example examples = 5;
   */
  examples: Example[];

  /**
   * @generated from field: string deprecated_message = 6;
   */
  deprecatedMessage: string;
};

/**
 * Describes the message autokitteh.module.v1.Function.
 * Use `create(FunctionSchema)` to create a new message.
 */
export const FunctionSchema: GenMessage<Function> = /*@__PURE__*/
  messageDesc(file_autokitteh_module_v1_module, 2);

/**
 * @generated from message autokitteh.module.v1.FunctionField
 */
export type FunctionField = Message<"autokitteh.module.v1.FunctionField"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * Flexible informative annotation, not parsed.
   *
   * @generated from field: string type = 3;
   */
  type: string;

  /**
   * @generated from field: bool optional = 4;
   */
  optional: boolean;

  /**
   * @generated from field: string default_value = 5;
   */
  defaultValue: string;

  /**
   * @generated from field: bool kwarg = 6;
   */
  kwarg: boolean;

  /**
   * @generated from field: repeated autokitteh.module.v1.Example examples = 7;
   */
  examples: Example[];
};

/**
 * Describes the message autokitteh.module.v1.FunctionField.
 * Use `create(FunctionFieldSchema)` to create a new message.
 */
export const FunctionFieldSchema: GenMessage<FunctionField> = /*@__PURE__*/
  messageDesc(file_autokitteh_module_v1_module, 3);

/**
 * @generated from message autokitteh.module.v1.Example
 */
export type Example = Message<"autokitteh.module.v1.Example"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * Optional.
   *
   * @generated from field: string explanation = 2;
   */
  explanation: string;
};

/**
 * Describes the message autokitteh.module.v1.Example.
 * Use `create(ExampleSchema)` to create a new message.
 */
export const ExampleSchema: GenMessage<Example> = /*@__PURE__*/
  messageDesc(file_autokitteh_module_v1_module, 4);

