// @generated by protoc-gen-es v1.5.1 with parameter "target=ts"
// @generated from file autokitteh/runner_manager/v1/runner_manager_svc.proto (package autokitteh.runner_manager.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message autokitteh.runner_manager.v1.ContainerConfig
 */
export class ContainerConfig extends Message<ContainerConfig> {
  /**
   * TBD by @efiShtain
   *
   * @generated from field: string image = 1;
   */
  image = "";

  constructor(data?: PartialMessage<ContainerConfig>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "autokitteh.runner_manager.v1.ContainerConfig";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "image", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ContainerConfig {
    return new ContainerConfig().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ContainerConfig {
    return new ContainerConfig().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ContainerConfig {
    return new ContainerConfig().fromJsonString(jsonString, options);
  }

  static equals(a: ContainerConfig | PlainMessage<ContainerConfig> | undefined, b: ContainerConfig | PlainMessage<ContainerConfig> | undefined): boolean {
    return proto3.util.equals(ContainerConfig, a, b);
  }
}

/**
 * TODO: Will become Start once we split to files
 * Tell runner manager to start a runner
 *
 * @generated from message autokitteh.runner_manager.v1.StartRunnerRequest
 */
export class StartRunnerRequest extends Message<StartRunnerRequest> {
  /**
   * @generated from field: autokitteh.runner_manager.v1.ContainerConfig container_config = 1;
   */
  containerConfig?: ContainerConfig;

  /**
   * user code as tar archive
   *
   * @generated from field: bytes build_artifact = 2;
   */
  buildArtifact = new Uint8Array(0);

  /**
   * vars from manifest, secrets and connections
   *
   * @generated from field: map<string, string> vars = 3;
   */
  vars: { [key: string]: string } = {};

  /**
   * @generated from field: string worker_address = 4;
   */
  workerAddress = "";

  constructor(data?: PartialMessage<StartRunnerRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "autokitteh.runner_manager.v1.StartRunnerRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "container_config", kind: "message", T: ContainerConfig },
    { no: 2, name: "build_artifact", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 3, name: "vars", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 4, name: "worker_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartRunnerRequest {
    return new StartRunnerRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartRunnerRequest {
    return new StartRunnerRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartRunnerRequest {
    return new StartRunnerRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StartRunnerRequest | PlainMessage<StartRunnerRequest> | undefined, b: StartRunnerRequest | PlainMessage<StartRunnerRequest> | undefined): boolean {
    return proto3.util.equals(StartRunnerRequest, a, b);
  }
}

/**
 * @generated from message autokitteh.runner_manager.v1.StartRunnerResponse
 */
export class StartRunnerResponse extends Message<StartRunnerResponse> {
  /**
   * @generated from field: string runner_id = 1;
   */
  runnerId = "";

  /**
   * @generated from field: string runner_address = 2;
   */
  runnerAddress = "";

  /**
   * @generated from field: string error = 3;
   */
  error = "";

  constructor(data?: PartialMessage<StartRunnerResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "autokitteh.runner_manager.v1.StartRunnerResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "runner_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "runner_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartRunnerResponse {
    return new StartRunnerResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartRunnerResponse {
    return new StartRunnerResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartRunnerResponse {
    return new StartRunnerResponse().fromJsonString(jsonString, options);
  }

  static equals(a: StartRunnerResponse | PlainMessage<StartRunnerResponse> | undefined, b: StartRunnerResponse | PlainMessage<StartRunnerResponse> | undefined): boolean {
    return proto3.util.equals(StartRunnerResponse, a, b);
  }
}

/**
 * @generated from message autokitteh.runner_manager.v1.RunnerHealthRequest
 */
export class RunnerHealthRequest extends Message<RunnerHealthRequest> {
  /**
   * @generated from field: string runner_id = 1;
   */
  runnerId = "";

  constructor(data?: PartialMessage<RunnerHealthRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "autokitteh.runner_manager.v1.RunnerHealthRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "runner_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RunnerHealthRequest {
    return new RunnerHealthRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RunnerHealthRequest {
    return new RunnerHealthRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RunnerHealthRequest {
    return new RunnerHealthRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RunnerHealthRequest | PlainMessage<RunnerHealthRequest> | undefined, b: RunnerHealthRequest | PlainMessage<RunnerHealthRequest> | undefined): boolean {
    return proto3.util.equals(RunnerHealthRequest, a, b);
  }
}

/**
 * @generated from message autokitteh.runner_manager.v1.RunnerHealthResponse
 */
export class RunnerHealthResponse extends Message<RunnerHealthResponse> {
  /**
   * @generated from field: bool healthy = 1;
   */
  healthy = false;

  /**
   * @generated from field: string error = 2;
   */
  error = "";

  constructor(data?: PartialMessage<RunnerHealthResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "autokitteh.runner_manager.v1.RunnerHealthResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "healthy", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RunnerHealthResponse {
    return new RunnerHealthResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RunnerHealthResponse {
    return new RunnerHealthResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RunnerHealthResponse {
    return new RunnerHealthResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RunnerHealthResponse | PlainMessage<RunnerHealthResponse> | undefined, b: RunnerHealthResponse | PlainMessage<RunnerHealthResponse> | undefined): boolean {
    return proto3.util.equals(RunnerHealthResponse, a, b);
  }
}

/**
 * @generated from message autokitteh.runner_manager.v1.StopRunnerRequest
 */
export class StopRunnerRequest extends Message<StopRunnerRequest> {
  /**
   * @generated from field: string runner_id = 1;
   */
  runnerId = "";

  constructor(data?: PartialMessage<StopRunnerRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "autokitteh.runner_manager.v1.StopRunnerRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "runner_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StopRunnerRequest {
    return new StopRunnerRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StopRunnerRequest {
    return new StopRunnerRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StopRunnerRequest {
    return new StopRunnerRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StopRunnerRequest | PlainMessage<StopRunnerRequest> | undefined, b: StopRunnerRequest | PlainMessage<StopRunnerRequest> | undefined): boolean {
    return proto3.util.equals(StopRunnerRequest, a, b);
  }
}

/**
 * @generated from message autokitteh.runner_manager.v1.StopRunnerResponse
 */
export class StopRunnerResponse extends Message<StopRunnerResponse> {
  /**
   * @generated from field: string error = 1;
   */
  error = "";

  constructor(data?: PartialMessage<StopRunnerResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "autokitteh.runner_manager.v1.StopRunnerResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StopRunnerResponse {
    return new StopRunnerResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StopRunnerResponse {
    return new StopRunnerResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StopRunnerResponse {
    return new StopRunnerResponse().fromJsonString(jsonString, options);
  }

  static equals(a: StopRunnerResponse | PlainMessage<StopRunnerResponse> | undefined, b: StopRunnerResponse | PlainMessage<StopRunnerResponse> | undefined): boolean {
    return proto3.util.equals(StopRunnerResponse, a, b);
  }
}

/**
 * @generated from message autokitteh.runner_manager.v1.HealthRequest
 */
export class HealthRequest extends Message<HealthRequest> {
  constructor(data?: PartialMessage<HealthRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "autokitteh.runner_manager.v1.HealthRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HealthRequest {
    return new HealthRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HealthRequest {
    return new HealthRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HealthRequest {
    return new HealthRequest().fromJsonString(jsonString, options);
  }

  static equals(a: HealthRequest | PlainMessage<HealthRequest> | undefined, b: HealthRequest | PlainMessage<HealthRequest> | undefined): boolean {
    return proto3.util.equals(HealthRequest, a, b);
  }
}

/**
 * @generated from message autokitteh.runner_manager.v1.HealthResponse
 */
export class HealthResponse extends Message<HealthResponse> {
  /**
   * @generated from field: string error = 1;
   */
  error = "";

  constructor(data?: PartialMessage<HealthResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "autokitteh.runner_manager.v1.HealthResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HealthResponse {
    return new HealthResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HealthResponse {
    return new HealthResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HealthResponse {
    return new HealthResponse().fromJsonString(jsonString, options);
  }

  static equals(a: HealthResponse | PlainMessage<HealthResponse> | undefined, b: HealthResponse | PlainMessage<HealthResponse> | undefined): boolean {
    return proto3.util.equals(HealthResponse, a, b);
  }
}

