# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: autokitteh/remote/v1/types.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n autokitteh/remote/v1/types.proto\x12\x14\x61utokitteh.remote.v1\"c\n\x05\x46rame\x12\x1a\n\x08\x66ilename\x18\x01 \x01(\tR\x08\x66ilename\x12\x16\n\x06lineno\x18\x02 \x01(\rR\x06lineno\x12\x12\n\x04\x63ode\x18\x03 \x01(\tR\x04\x63ode\x12\x12\n\x04name\x18\x04 \x01(\tR\x04name\"\x1b\n\x05\x45vent\x12\x12\n\x04\x64\x61ta\x18\x01 \x01(\x0cR\x04\x64\x61taB\xe1\x01\n\x18\x63om.autokitteh.remote.v1B\nTypesProtoP\x01ZGgo.autokitteh.dev/autokitteh/proto/gen/go/autokitteh/remote/v1;remotev1\xa2\x02\x03\x41RX\xaa\x02\x14\x41utokitteh.Remote.V1\xca\x02\x14\x41utokitteh\\Remote\\V1\xe2\x02 Autokitteh\\Remote\\V1\\GPBMetadata\xea\x02\x16\x41utokitteh::Remote::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autokitteh.remote.v1.types_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030com.autokitteh.remote.v1B\nTypesProtoP\001ZGgo.autokitteh.dev/autokitteh/proto/gen/go/autokitteh/remote/v1;remotev1\242\002\003ARX\252\002\024Autokitteh.Remote.V1\312\002\024Autokitteh\\Remote\\V1\342\002 Autokitteh\\Remote\\V1\\GPBMetadata\352\002\026Autokitteh::Remote::V1'
  _globals['_FRAME']._serialized_start=58
  _globals['_FRAME']._serialized_end=157
  _globals['_EVENT']._serialized_start=159
  _globals['_EVENT']._serialized_end=186
# @@protoc_insertion_point(module_scope)
