# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import user_code_handler_svc_pb2 as autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2


class UserCodeHandlerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Activity = channel.unary_unary(
                '/autokitteh.remote.v1.UserCodeHandlerService/Activity',
                request_serializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.ActivityRequest.SerializeToString,
                response_deserializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.ActivityResponse.FromString,
                _registered_method=True)
        self.Done = channel.unary_unary(
                '/autokitteh.remote.v1.UserCodeHandlerService/Done',
                request_serializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.DoneRequest.SerializeToString,
                response_deserializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.DoneResponse.FromString,
                _registered_method=True)
        self.Log = channel.unary_unary(
                '/autokitteh.remote.v1.UserCodeHandlerService/Log',
                request_serializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.LogRequest.SerializeToString,
                response_deserializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.LogResponse.FromString,
                _registered_method=True)
        self.Print = channel.unary_unary(
                '/autokitteh.remote.v1.UserCodeHandlerService/Print',
                request_serializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.PrintRequest.SerializeToString,
                response_deserializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.PrintResponse.FromString,
                _registered_method=True)
        self.Sleep = channel.unary_unary(
                '/autokitteh.remote.v1.UserCodeHandlerService/Sleep',
                request_serializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.SleepRequest.SerializeToString,
                response_deserializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.SleepResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_unary(
                '/autokitteh.remote.v1.UserCodeHandlerService/Subscribe',
                request_serializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.SubscribeResponse.FromString,
                _registered_method=True)
        self.NextEvent = channel.unary_unary(
                '/autokitteh.remote.v1.UserCodeHandlerService/NextEvent',
                request_serializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.NextEventRequest.SerializeToString,
                response_deserializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.NextEventResponse.FromString,
                _registered_method=True)
        self.Unsubscribe = channel.unary_unary(
                '/autokitteh.remote.v1.UserCodeHandlerService/Unsubscribe',
                request_serializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.UnsubscribeRequest.SerializeToString,
                response_deserializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.UnsubscribeResponse.FromString,
                _registered_method=True)
        self.StartSession = channel.unary_unary(
                '/autokitteh.remote.v1.UserCodeHandlerService/StartSession',
                request_serializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.StartSessionRequest.SerializeToString,
                response_deserializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.StartSessionResponse.FromString,
                _registered_method=True)
        self.EncodeJWT = channel.unary_unary(
                '/autokitteh.remote.v1.UserCodeHandlerService/EncodeJWT',
                request_serializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.EncodeJWTRequest.SerializeToString,
                response_deserializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.EncodeJWTResponse.FromString,
                _registered_method=True)
        self.RefreshOAuthToken = channel.unary_unary(
                '/autokitteh.remote.v1.UserCodeHandlerService/RefreshOAuthToken',
                request_serializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.RefreshRequest.SerializeToString,
                response_deserializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.RefreshResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/autokitteh.remote.v1.UserCodeHandlerService/Health',
                request_serializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.UserCodeHandlerHealthRequest.SerializeToString,
                response_deserializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.UserCodeHandlerHealthResponse.FromString,
                _registered_method=True)
        self.IsActiveRunner = channel.unary_unary(
                '/autokitteh.remote.v1.UserCodeHandlerService/IsActiveRunner',
                request_serializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.IsActiveRunnerRequest.SerializeToString,
                response_deserializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.IsActiveRunnerResponse.FromString,
                _registered_method=True)


class UserCodeHandlerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Activity(self, request, context):
        """Runner starting activity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Done(self, request, context):
        """Runner done with activity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Log(self, request, context):
        """Session logs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Print(self, request, context):
        """Print to session log
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sleep(self, request, context):
        """ak functions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NextEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unsubscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EncodeJWT(self, request, context):
        """Utility functions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshOAuthToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsActiveRunner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserCodeHandlerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Activity': grpc.unary_unary_rpc_method_handler(
                    servicer.Activity,
                    request_deserializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.ActivityRequest.FromString,
                    response_serializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.ActivityResponse.SerializeToString,
            ),
            'Done': grpc.unary_unary_rpc_method_handler(
                    servicer.Done,
                    request_deserializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.DoneRequest.FromString,
                    response_serializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.DoneResponse.SerializeToString,
            ),
            'Log': grpc.unary_unary_rpc_method_handler(
                    servicer.Log,
                    request_deserializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.LogRequest.FromString,
                    response_serializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.LogResponse.SerializeToString,
            ),
            'Print': grpc.unary_unary_rpc_method_handler(
                    servicer.Print,
                    request_deserializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.PrintRequest.FromString,
                    response_serializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.PrintResponse.SerializeToString,
            ),
            'Sleep': grpc.unary_unary_rpc_method_handler(
                    servicer.Sleep,
                    request_deserializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.SleepRequest.FromString,
                    response_serializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.SleepResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.SubscribeRequest.FromString,
                    response_serializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.SubscribeResponse.SerializeToString,
            ),
            'NextEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.NextEvent,
                    request_deserializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.NextEventRequest.FromString,
                    response_serializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.NextEventResponse.SerializeToString,
            ),
            'Unsubscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Unsubscribe,
                    request_deserializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.UnsubscribeRequest.FromString,
                    response_serializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.UnsubscribeResponse.SerializeToString,
            ),
            'StartSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSession,
                    request_deserializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.StartSessionRequest.FromString,
                    response_serializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.StartSessionResponse.SerializeToString,
            ),
            'EncodeJWT': grpc.unary_unary_rpc_method_handler(
                    servicer.EncodeJWT,
                    request_deserializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.EncodeJWTRequest.FromString,
                    response_serializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.EncodeJWTResponse.SerializeToString,
            ),
            'RefreshOAuthToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshOAuthToken,
                    request_deserializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.RefreshRequest.FromString,
                    response_serializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.RefreshResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.UserCodeHandlerHealthRequest.FromString,
                    response_serializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.UserCodeHandlerHealthResponse.SerializeToString,
            ),
            'IsActiveRunner': grpc.unary_unary_rpc_method_handler(
                    servicer.IsActiveRunner,
                    request_deserializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.IsActiveRunnerRequest.FromString,
                    response_serializer=autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.IsActiveRunnerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autokitteh.remote.v1.UserCodeHandlerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('autokitteh.remote.v1.UserCodeHandlerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserCodeHandlerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Activity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autokitteh.remote.v1.UserCodeHandlerService/Activity',
            autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.ActivityRequest.SerializeToString,
            autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.ActivityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Done(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autokitteh.remote.v1.UserCodeHandlerService/Done',
            autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.DoneRequest.SerializeToString,
            autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.DoneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Log(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autokitteh.remote.v1.UserCodeHandlerService/Log',
            autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.LogRequest.SerializeToString,
            autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.LogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Print(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autokitteh.remote.v1.UserCodeHandlerService/Print',
            autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.PrintRequest.SerializeToString,
            autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.PrintResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sleep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autokitteh.remote.v1.UserCodeHandlerService/Sleep',
            autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.SleepRequest.SerializeToString,
            autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.SleepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autokitteh.remote.v1.UserCodeHandlerService/Subscribe',
            autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.SubscribeRequest.SerializeToString,
            autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.SubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NextEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autokitteh.remote.v1.UserCodeHandlerService/NextEvent',
            autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.NextEventRequest.SerializeToString,
            autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.NextEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unsubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autokitteh.remote.v1.UserCodeHandlerService/Unsubscribe',
            autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.UnsubscribeRequest.SerializeToString,
            autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.UnsubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autokitteh.remote.v1.UserCodeHandlerService/StartSession',
            autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.StartSessionRequest.SerializeToString,
            autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.StartSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EncodeJWT(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autokitteh.remote.v1.UserCodeHandlerService/EncodeJWT',
            autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.EncodeJWTRequest.SerializeToString,
            autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.EncodeJWTResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshOAuthToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autokitteh.remote.v1.UserCodeHandlerService/RefreshOAuthToken',
            autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.RefreshRequest.SerializeToString,
            autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.RefreshResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autokitteh.remote.v1.UserCodeHandlerService/Health',
            autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.UserCodeHandlerHealthRequest.SerializeToString,
            autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.UserCodeHandlerHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsActiveRunner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autokitteh.remote.v1.UserCodeHandlerService/IsActiveRunner',
            autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.IsActiveRunnerRequest.SerializeToString,
            autokitteh_dot_remote_dot_v1_dot_user__code__handler__svc__pb2.IsActiveRunnerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
