name: CI - GORM

on:
  pull_request:
    paths:
      - "internal/backend/db/dbgorm/**"

jobs:
  test-gorm:
    name: GORM
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run GORM tests on all engines
        run: make test-dbgorm
