name: Build Image
concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: false

on:
    push:
        branches: [main]
    pull_request:

jobs:
    build-standard:
        uses: ./.github/workflows/docker.yml
        with:
            push: ${{ github.event_name == 'push' }}
            image: server
        secrets: inherit
    build-ee:
        uses: ./.github/workflows/docker.yml
        with:
            push: ${{ github.event_name == 'push' }}
            image: ee/server
            buildTags: "enterprise"
        secrets: inherit
