# See also "docker-pr.yml", "manual-docker-image.yml", and "release.yml".
# https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
# https://github.com/marketplace/actions/amazon-ecr-login-action-for-github-actions
# https://github.com/marketplace/actions/build-and-push-docker-images

name: CI - Docker (main)

on:
  push:
    branches: [main]

jobs:
  publish-latest-docker-image:
    name: Publish Docker image
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup version info
        run: |
          # These are consumed in the Dockerfile.
          echo "${GITHUB_REF_NAME}" > .version
          echo "${GITHUB_SHA}" > .commit

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_GITHUB_ROLE}}
          role-session-name: Github_Action_Release_Autokitteh
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          tags: ${{steps.login-ecr.outputs.registry}}/autokitteh:latest
          push: true
          provenance: false
