# See also "docker-pr.yml", "manual-docker-image.yml", and "release.yml".
# https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
# https://github.com/marketplace/actions/amazon-ecr-login-action-for-github-actions
# https://github.com/marketplace/actions/build-and-push-docker-images

name: CI - Docker (main)
concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: false

on:
    push:
        branches: [main]
    pull_request:

jobs:
    build-standard:
        uses: ./.github/workflows/docker.yml
        with:
            push: ${{ github.event_name == 'push' }}
            image: server
            buildTags: ""
        secrets: inherit
    build-ee:
        uses: ./.github/workflows/docker.yml
        with:
            push: ${{ github.event_name == 'push' }}
            image: ee/server
            buildTags: "-tags=enterprise"
        secrets: inherit
