name: CI - Python

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test-go:
    name: Python runtime Go tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Test
        run: gotestsum -f testname -- ./runtimes/pythonrt/...

  test-python:
    name: Python tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: make -C runtimes/pythonrt/runner install-deps

      - name: Test
        run: |
          cd runtimes/pythonrt/runner
          make install-deps
          python -m pytest

  test-sessions:
    name: Python session tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build
        run: go build -o bin/ak ./cmd/ak

      - name: Test
        run: ./tests/sessions/run.sh
