# https://github.com/marketplace/actions/setup-go-environment
# https://github.com/marketplace/actions/setup-python

name: CI - Python

on:
  pull_request:
  push:
    branches: [main]

jobs:
  python-runtime-go-tests:
    name: Python runtime Go tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Test
        run: gotestsum -f github-actions -- -trimpath ./runtimes/pythonrt/...

  python-unit-tests:
    name: Python unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12" # Should be in sync with runtimes/pythonrt/pythonrt.go:minPyVersion
      - name: Test
        run: cd runtimes/pythonrt && make ci

  python-session-tests:
    name: Python Session tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build AK
        run: go build -trimpath -o bin/ak ./cmd/ak

      - name: Test
        run: PYTHON=only ./tests/sessions/run.sh
