# https://github.com/marketplace/actions/setup-python
# https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md
# https://github.com/marketplace/actions/astral-sh-setup-uv
# https://docs.astral.sh/uv/guides/integration/github/

name: CI - Python

on:
  pull_request:
  push:
    branches: [main]

jobs:
  python-runtime-go-tests:
    name: Python runtime Go tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Download Go modules
        run: go mod download
      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Test
        run: gotestsum -f github-actions -- -trimpath ./runtimes/pythonrt/...

  python-unit-tests:
    name: Python unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Test
        run: cd runtimes/pythonrt && make ci

  python-session-tests:
    name: Python Session tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Download Go modules
        run: go mod download
      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Build AK
        run: go build -trimpath -o bin/ak ./cmd/ak

      - name: Test
        run: gotestsum -f github-actions --
              -timeout 0 -trimpath ./tests/sessions/... -run /python

  python-SDK-tests:
    name: Python SDK tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Test
        run: cd runtimes/pythonrt/py-sdk && make ci
