name: CI - Python

on:
  pull_request:
  push:
    branches: [main]

jobs:
  python-go-tests:
    name: Python runtime Go tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Test
        run: gotestsum -f testname -- -trimpath ./runtimes/pythonrt/...

  python-unit-tests:
    if: false # Temporarily disabled, tests fail due to missing AK SDK.
    name: Python tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: make -C runtimes/pythonrt/runner install-deps

      - name: Test
        run: cd runtimes/pythonrt/runner && python -m pytest

  python-session-tests:
    name: Python session tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build
        run: go build -trimpath -o bin/ak ./cmd/ak

      - name: Test
        run: PYTHON=only ./tests/sessions/run.sh

  python-static-analysis:
    name: Python static analysis
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # TODO: Ruff + doc changes check
