# https://github.com/marketplace/actions/setup-go-environment
# https://github.com/marketplace/actions/setup-python
# https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md
# https://docs.astral.sh/uv/guides/integration/github/

name: CI - Python

on:
  pull_request:
  push:
    branches: [main]

jobs:
  python-runtime-go-tests:
    if: false
    name: Python runtime Go tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Download Go modules
        run: go mod download
      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Test
        run: gotestsum -f github-actions -- -trimpath ./runtimes/pythonrt/...

  python-unit-tests:
    if: false
    name: Python unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Test
        run: cd runtimes/pythonrt && make ci

  python-session-tests:
    name: Python Session tests
    runs-on: ubuntu-latest
    timeout-minutes: 30  # TODO(ENG-2037): 10
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          cenable-cache: true
          cache-dependency-glob: "**/requirements.txt"
      - name: Download Go modules
        run: go mod download
      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      # - name: Build AK
      #   run: go build -trimpath -o bin/ak ./cmd/ak

      - name: Warm up virtual environment
        run: |
          uv pip install -r runtimes/pythonrt/py-sdk/docs/requirements.txt
          echo $VIRTUAL_ENV
          echo $UV_SYSTEM_PYTHON
          export
        env:
          UV_SYSTEM_PYTHON: 1

      # TODO(ENG-2037): Re-enable timeout (default 10m or custom one).
      # - name: Test
      #   run: gotestsum -f github-actions -- -timeout 0 -trimpath ./tests/sessions/... -run /python
